
server:
  port: 8081

spring:
  application:
    name: order-microservice
    facility-num: 5

  datasource:
    url: jdbc:postgresql://localhost:5432/graylog-publisher
    username: graylog-publisher_user
    password: graylog-publisher
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://localhost:8085

    topic:
      order: microservice-order
      invoice: microservice-invoice
      graylog: graylog-publisher

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: order-microservice-group
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true