
spring:
  application:
    name: graylogpub-microservice
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888  # URL of the Config Server
      label: master  # The label (branch) of the config repository, typically 'master' or a custom one
      profile: dev  # The profile to load configuration for (e.g., dev, prod)
      failFast: true