
spring:
  application:
    name: graylogpub-microservice
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      label: master
      profile: dev
      failFast: true