spring:
  application:
    name: myproject-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreazemi94/Kafka-Graylog
          clone-on-start: true
          default-label: master
          search-paths:
            - resources/dev
server:
  port: 8888
