/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.myproject.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InvoiceDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7989623894271921312L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InvoiceDTO\",\"namespace\":\"com.myproject.dto\",\"fields\":[{\"name\":\"invoiceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"customerId\",\"type\":\"long\"},{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"invoiceDate\",\"type\":\"long\"},{\"name\":\"totalAmount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InvoiceDTO> ENCODER =
      new BinaryMessageEncoder<InvoiceDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InvoiceDTO> DECODER =
      new BinaryMessageDecoder<InvoiceDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InvoiceDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InvoiceDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InvoiceDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InvoiceDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InvoiceDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InvoiceDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InvoiceDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InvoiceDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String invoiceId;
   private long customerId;
   private long orderId;
   private long invoiceDate;
   private double totalAmount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InvoiceDTO() {}

  /**
   * All-args constructor.
   * @param invoiceId The new value for invoiceId
   * @param customerId The new value for customerId
   * @param orderId The new value for orderId
   * @param invoiceDate The new value for invoiceDate
   * @param totalAmount The new value for totalAmount
   */
  public InvoiceDTO(java.lang.String invoiceId, java.lang.Long customerId, java.lang.Long orderId, java.lang.Long invoiceDate, java.lang.Double totalAmount) {
    this.invoiceId = invoiceId;
    this.customerId = customerId;
    this.orderId = orderId;
    this.invoiceDate = invoiceDate;
    this.totalAmount = totalAmount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return invoiceId;
    case 1: return customerId;
    case 2: return orderId;
    case 3: return invoiceDate;
    case 4: return totalAmount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: invoiceId = value$ != null ? value$.toString() : null; break;
    case 1: customerId = (java.lang.Long)value$; break;
    case 2: orderId = (java.lang.Long)value$; break;
    case 3: invoiceDate = (java.lang.Long)value$; break;
    case 4: totalAmount = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'invoiceId' field.
   * @return The value of the 'invoiceId' field.
   */
  public java.lang.String getInvoiceId() {
    return invoiceId;
  }


  /**
   * Sets the value of the 'invoiceId' field.
   * @param value the value to set.
   */
  public void setInvoiceId(java.lang.String value) {
    this.invoiceId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public long getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(long value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public long getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'invoiceDate' field.
   * @return The value of the 'invoiceDate' field.
   */
  public long getInvoiceDate() {
    return invoiceDate;
  }


  /**
   * Sets the value of the 'invoiceDate' field.
   * @param value the value to set.
   */
  public void setInvoiceDate(long value) {
    this.invoiceDate = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return The value of the 'totalAmount' field.
   */
  public double getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * @param value the value to set.
   */
  public void setTotalAmount(double value) {
    this.totalAmount = value;
  }

  /**
   * Creates a new InvoiceDTO RecordBuilder.
   * @return A new InvoiceDTO RecordBuilder
   */
  public static com.myproject.dto.InvoiceDTO.Builder newBuilder() {
    return new com.myproject.dto.InvoiceDTO.Builder();
  }

  /**
   * Creates a new InvoiceDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InvoiceDTO RecordBuilder
   */
  public static com.myproject.dto.InvoiceDTO.Builder newBuilder(com.myproject.dto.InvoiceDTO.Builder other) {
    if (other == null) {
      return new com.myproject.dto.InvoiceDTO.Builder();
    } else {
      return new com.myproject.dto.InvoiceDTO.Builder(other);
    }
  }

  /**
   * Creates a new InvoiceDTO RecordBuilder by copying an existing InvoiceDTO instance.
   * @param other The existing instance to copy.
   * @return A new InvoiceDTO RecordBuilder
   */
  public static com.myproject.dto.InvoiceDTO.Builder newBuilder(com.myproject.dto.InvoiceDTO other) {
    if (other == null) {
      return new com.myproject.dto.InvoiceDTO.Builder();
    } else {
      return new com.myproject.dto.InvoiceDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for InvoiceDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InvoiceDTO>
    implements org.apache.avro.data.RecordBuilder<InvoiceDTO> {

    private java.lang.String invoiceId;
    private long customerId;
    private long orderId;
    private long invoiceDate;
    private double totalAmount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.myproject.dto.InvoiceDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.invoiceId)) {
        this.invoiceId = data().deepCopy(fields()[0].schema(), other.invoiceId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.invoiceDate)) {
        this.invoiceDate = data().deepCopy(fields()[3].schema(), other.invoiceDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing InvoiceDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.myproject.dto.InvoiceDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.invoiceId)) {
        this.invoiceId = data().deepCopy(fields()[0].schema(), other.invoiceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.invoiceDate)) {
        this.invoiceDate = data().deepCopy(fields()[3].schema(), other.invoiceDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'invoiceId' field.
      * @return The value.
      */
    public java.lang.String getInvoiceId() {
      return invoiceId;
    }


    /**
      * Sets the value of the 'invoiceId' field.
      * @param value The value of 'invoiceId'.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder setInvoiceId(java.lang.String value) {
      validate(fields()[0], value);
      this.invoiceId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'invoiceId' field has been set.
      * @return True if the 'invoiceId' field has been set, false otherwise.
      */
    public boolean hasInvoiceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'invoiceId' field.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder clearInvoiceId() {
      invoiceId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public long getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder setCustomerId(long value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder clearCustomerId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public long getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder setOrderId(long value) {
      validate(fields()[2], value);
      this.orderId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder clearOrderId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'invoiceDate' field.
      * @return The value.
      */
    public long getInvoiceDate() {
      return invoiceDate;
    }


    /**
      * Sets the value of the 'invoiceDate' field.
      * @param value The value of 'invoiceDate'.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder setInvoiceDate(long value) {
      validate(fields()[3], value);
      this.invoiceDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'invoiceDate' field has been set.
      * @return True if the 'invoiceDate' field has been set, false otherwise.
      */
    public boolean hasInvoiceDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'invoiceDate' field.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder clearInvoiceDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * @return The value.
      */
    public double getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder setTotalAmount(double value) {
      validate(fields()[4], value);
      this.totalAmount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * @return This builder.
      */
    public com.myproject.dto.InvoiceDTO.Builder clearTotalAmount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InvoiceDTO build() {
      try {
        InvoiceDTO record = new InvoiceDTO();
        record.invoiceId = fieldSetFlags()[0] ? this.invoiceId : (java.lang.String) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.Long) defaultValue(fields()[1]);
        record.orderId = fieldSetFlags()[2] ? this.orderId : (java.lang.Long) defaultValue(fields()[2]);
        record.invoiceDate = fieldSetFlags()[3] ? this.invoiceDate : (java.lang.Long) defaultValue(fields()[3]);
        record.totalAmount = fieldSetFlags()[4] ? this.totalAmount : (java.lang.Double) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InvoiceDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<InvoiceDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InvoiceDTO>
    READER$ = (org.apache.avro.io.DatumReader<InvoiceDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.invoiceId);

    out.writeLong(this.customerId);

    out.writeLong(this.orderId);

    out.writeLong(this.invoiceDate);

    out.writeDouble(this.totalAmount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.invoiceId = in.readString();

      this.customerId = in.readLong();

      this.orderId = in.readLong();

      this.invoiceDate = in.readLong();

      this.totalAmount = in.readDouble();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.invoiceId = in.readString();
          break;

        case 1:
          this.customerId = in.readLong();
          break;

        case 2:
          this.orderId = in.readLong();
          break;

        case 3:
          this.invoiceDate = in.readLong();
          break;

        case 4:
          this.totalAmount = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










